### ISSUE TITLE
toolchain_install.bash errors

### ISSUE THREAD

**Issue by jeppenodgaard** [andersdra/docker-mplabx#1]
There are some issues with the script with old versions of xc32. They come as a tar file and the xc32-installer does not have a LicenseType option.
There's also an issue with PIC32 legacy installation due to spaces.

**Comment by jeppenodgaard** [comment]
I've opened https://github.com/andersdra/docker-mplabx/pull/2 to attempt to fix the issues

**Comment by andersdra** [comment]
Thanks a lot for your contributions! My testing is very limited as I only use IDE + avrgcc. Now I will be faced with another challenge, how to get this back to gitlab without messing up..

**Comment by jeppenodgaard** [comment]
I'm glad they were useful :)
I'm not sure I understand what you mean? The pull request should already be part of your repository.

**Comment by andersdra** [comment]
Will test them later on, now I'm just excited someone actually submitted a
PR :) I am very noob when it comes to git but I managed to update the
gitlab repo by adding github as a new remote, pulled the changes and then
pushed back to gitlab

ons. 11. des. 2019, 08:53 skrev jeppenodgaard <notifications@github.com>:
